# Generated by Django 3.1.2 on 2020-12-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_update',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=15)),
                ('shift', models.CharField(max_length=5)),
                ('employee_number', models.CharField(max_length=10)),
                ('component_type', models.CharField(max_length=25)),
                ('component_lk_number', models.CharField(max_length=25)),
                ('component_lot_number', models.CharField(max_length=5)),
                ('component_quantity', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
