# Generated by Django 3.1.2 on 2020-12-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laser_production_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Components',
            fields=[
                ('main_id', models.AutoField(primary_key=True, serialize=False)),
                ('component_type', models.CharField(max_length=25)),
                ('component_lk_number', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
